export const SurfTeam = [
  {
    id: 1,
    confirm: false,
    full_name: "Muklis Anwar",
    nickname: "",
    title: "surf coach",
    certificated: "ISA",
    isa: true,
    age: 1998,
    level: "ISA Level 1",
    experience: "",
    location: "Medewi",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/muklis_.anwar",
    user_soorfinc: "",
    archievement: [
      {
        title: "ISA Surf Judge",
      },
    ],
  },
  {
    id: 2,
    confirm: false,
    full_name: "Muz Jeksen",
    nickname: "",
    title: "surf coach",
    certificated: "ISA",
    isa: true,
    age: 1998,
    level: "ISA Level 1",
    experience: "",
    location: "Hallway",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/musjeksen",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 3,
    confirm: false,
    full_name: "I Made Agus Setyawan",
    nickname: "",
    title: "surf coach",
    certificated: "ISA",
    isa: true,
    age: 1998,
    level: "ISA Level 1",
    experience: "",
    location: "Uluwatu",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/gus_bentir",
    user_soorfinc: "",
    archievement: [
      {
        title:
          "Pro Surfer: Open Men's Champion ASC (Winner Mens Open Rip Curl Surf and Music Festival (2009)",
      },
      {
        title: "Coca-cola Indonesian Surf Championship Winner (2012)",
      },
      {
        title: "Monsoon Mayhem International Surf Challenge winner (2012)",
      },
    ],
  },
  {
    id: 4,
    confirm: false,
    full_name: "Raditya Rondi",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "7 years to be coach",
    location: "Kuta",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/radityarondi",
    user_soorfinc: "",
    archievement: [
      {
        title:
          "Pro Surfer: Open Men's Champion ASC (Winner Mens Open Rip Curl Surf and Music Festival (2009)",
      },
      {
        title: "Coca-cola Indonesian Surf Championship Winner (2012)",
      },
      {
        title: "Monsoon Mayhem International Surf Challenge winner (2012)",
      },
    ],
  },
  {
    id: 5,
    confirm: false,
    full_name: "Oney Anwar",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Canggu",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/oneyanwar",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer: First Indonesian surfer to qualify for the World Surf League (WSL)",
      },
    ],
  },
  {
    id: 6,
    confirm: false,
    full_name: "Dharma Putra Tonjo",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Legian",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/darmaputratonjo",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 7,
    confirm: false,
    full_name: "Putra Pulu",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Lembongan",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/putrapulu",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer: 2010 Indonesian Surf Champion",
      },
    ],
  },
  {
    id: 8,
    confirm: false,
    full_name: "Dede Suryana",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Cimaja",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/mankdede",
    user_soorfinc: "",
    archievement: [
      {
        title:
          "Pro Surfer: 2008 ISC Winner, 2008 Asian Beach Games: Gold-Air, Gold-Team, Youth Achievement award",
      },
    ],
  },
  {
    id: 9,
    confirm: false,
    full_name: "Gogo Sujaya",
    nickname: "",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Kuta Reef",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/gogosujaya",
    user_soorfinc: "",
    archievement: [
      {
        title: "",
      },
    ],
  },
  {
    id: 10,
    confirm: false,
    full_name: "Dharma Yasa",
    nickname: "Blerong",
    title: "surf coach",
    certificated: "no ISA",
    isa: false,
    age: 1998,
    level: "Pro Surfer",
    experience: "",
    location: "Legian",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/darmayasablerok",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 11,
    confirm: true,
    full_name: "Dedi Santosa",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Kuta / Canggu",
    profile: "/assets/team/Dedi Santosa.png",
    user_instagram: "https://www.instagram.com/dedisantosa_",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 12,
    confirm: false,
    full_name: "Mickey Sudena",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Hallway",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/sudenasurfcoach",
    user_soorfinc: "",
    archievement: [
      {
        title: "",
      },
    ],
  },
  {
    id: 13,
    confirm: false,
    full_name: "Danyel Amar",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Legian",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/danyel_amar",
    user_soorfinc: "",
    archievement: [
      {
        title: "",
      },
    ],
  },
  {
    id: 14,
    confirm: false,
    full_name: "Mega Artana",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Legian",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/mega_artana",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 15,
    confirm: false,
    full_name: "Garut Widiarta",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Legian",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/garut_widiarta",
    user_soorfinc: "",
    archievement: [
      {
        title: "Pro Surfer",
      },
    ],
  },
  {
    id: 16,
    confirm: false,
    full_name: "Kadek Murtika",
    nickname: "",
    title: "surf coach",
    certificated: "No ISA",
    isa: false,
    age: 1998,
    level: "Free Surfer",
    experience: "",
    location: "Pererenan",
    profile: "/assets/team/ASPA.png",
    user_instagram: "https://www.instagram.com/clepuk_balibagus",
    user_soorfinc: "",
    archievement: [
      {
        title: "",
      },
    ],
  },
]
