// data ini berelasi dengan src\app\lib\program\academy\DataBooking.ts
export const NewAcademyDataPrice = [
  {
    id: "a1-1",
    title: "High-Performance Surf Assessment 1:1 for Basic Price",
    pricing: 1500000,
    slug: "high-performance-surf-assessment-a1-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a1-2",
    title: "Price of High-Performance Physical Assessment + Surf Assessment",
    pricing: 2500000,
    slug: "high-performance-surf-assessment-a1-2",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a2-1",
    title: "Custom Surf Coaching Session 1:1 for 1 Session",
    pricing: 1200000,
    slug: "custom-surf-coaching-session-a2-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a2-2",
    title: "Custom Surf Coaching Session 1:1 for 5 Session",
    pricing: 5000000,
    slug: "custom-surf-coaching-session-a2-2",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a2-3",
    title: "Custom Surf Coaching Session 1:1 for 10 Session",
    pricing: 8500000,
    slug: "custom-surf-coaching-session-a2-3",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a3-1",
    title: "Elite Surf Coaching Pack 1:1 for 10 Sessions",
    pricing: 12000000,
    slug: "elite-surf-coaching-pack-a3-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "a4-1",
    title: "Group Surf Coaching Session for 1 Session",
    pricing: 450000,
    slug: "group-surf-coaching-session-a4-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b1-1",
    title: "High-Performance Physical Assessment 1:1 for basic price",
    pricing: 1500000,
    slug: "high-performance-physical-assessment-b1-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b1-2",
    title: "Price of High-Performance Physical Assessment + Surf Assessment",
    pricing: 2500000,
    slug: "high-performance-physical-assessment-b1-2",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b2-1",
    title: "Custom Physical Training Session 1:1 for 1 Session",
    pricing: 1200000,
    slug: "custom-physical-training-session-b2-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b2-2",
    title: "Custom Physical Training Session 1:1 for 10 Session",
    pricing: 10500000,
    slug: "custom-physical-training-session-b2-2",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b3-1",
    title: "Elite Physical Training Pack 1:1 for 10 Sessions",
    pricing: 12000000,
    slug: "elite-physical-training-pack-b3-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
  {
    id: "b4-1",
    title: "Group Physical Training Session for 1 Session starts from",
    pricing: 350000,
    slug: "group-physical-training-session-b4-1",
    paymentUrl: "https://asiansurfacademy.com",
  },
];
