import "./globals.css";
import type { Metadata } from "next";
import Navigation from "./Components/Navigation";

import { Inter } from "next/font/google";
import FooterPage from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={"font-satoshi text-base"}>
				<Navigation />
				{children}
				<FooterPage />
			</body>
		</html>
	);
}
