export const CoreTeam = [
	{
		id: 1,
		full_name: "Tipi Jabrik",
		nickname: "Tipi",
		Age: 1985,
		title: "ASPA Director",
		experient: "+10 years coach",
		location: "Badung",
		profile: "",
		img: "",
	},
	{
		id: 2,
		full_name: "Juan Gorostidi",
		nickname: "Juan",
		Age: 1998,
		title: "ASPA Manager",
		experient: "+5 years coach",
		location: "Bali",
		profile: "",
		img: "",
	},
	{
		id: 3,
		full_name: "Dylan Amar",
		nickname: "Dylan",
		Age: 1995,
		title: "ASPA Head coach",
		experient: "+5 years coach",
		location: "Bali",
		profile: "",
		img: "",
	},
];
export const ExpertTeam = [
	{
		id: 1,
		full_name: "Gabriela Mackanicova",
		title: "Fitness Coach",
		level: "Expert",
		location: "Trained Kelly Slater",
		profile: "",
		img: "",
	},
	{
		id: 2,
		full_name: "Kartika",
		title: "Nutrition",
		level: "Profile",
		location: "",
		profile: "",
		img: "",
	},
];

export const VideographerTeam = [
	{
		id: 1,
		full_name: "Harry Bali surf vision",
		title: "surf videographer",
		location: "uluwatu",
		profile: "",
		img: "",
	},
	{
		id: 2,
		full_name: "Made Ropik",
		title: "surf videographer",
		location: "uluwatu",
		profile: "",
		img: "",
	},
	{
		id: 3,
		full_name: "Vito",
		title: "all around",
		location: "",
		profile: "",
		img: "",
	},
	{
		id: 4,
		full_name: "Juni Setiawan",
		title: "all around",
		location: "",
		profile: "",
		img: "",
	},
];

export const SurfTeam = [
	{
		id: 1,
		full_name: "Muklis Anwar",
		title: "surf coach",
		certificated: "ISA",
		level: "ISA Level 1",
		location: "Medewi",
		profile: "",
		img: "",
	},
	{
		id: 2,
		full_name: "Muz Jeksen",
		title: "surf coach",
		certificated: "ISA",
		level: "ISA Level 1",
		location: "Hallway",
		profile: "",
		img: "",
	},
	{
		id: 3,
		full_name: "I Made Agus Setyawan",
		title: "surf coach",
		certificated: "ISA",
		level: "ISA Level 1",
		location: "Uluwatu",
		profile: "",
		img: "",
	},
	{
		id: 4,
		full_name: "Raditya Rondi",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Kuta",
		profile: "",
		img: "",
	},
	{
		id: 5,
		full_name: "Oney Anwar",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Canggu",
		profile: "",
		img: "",
	},
	{
		id: 6,
		full_name: "Dharma Putra Tonjo",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Legian",
		profile: "",
		img: "",
	},
	{
		id: 7,
		full_name: "Putra Pulu",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Lembongan",
		profile: "",
		img: "",
	},
	{
		id: 8,
		full_name: "Dede Suryana",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Cimaja",
		profile: "",
		img: "",
	},
	{
		id: 9,
		full_name: "Gogo Sujaya",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Kuta Reef",
		profile: "",
		img: "",
	},
	{
		id: 10,
		full_name: "Dharma Yasa (Blerong)",
		title: "surf coach",
		certificated: "no ISA",
		level: "Pro Surfer",
		location: "Legian",
		profile: "",
		img: "",
	},
	{
		id: 11,
		full_name: "Dedi Santosa",
		title: "surf coach",
		certificated: "No ISA",
		level: "Free Surfer",
		location: "Kuta / Canggu",
		profile: "",
		img: "",
	},
	{
		id: 12,
		full_name: "Mickey Sudena",
		title: "surf coach",
		certificated: "No ISA",
		level: "Free Surfer",
		location: "Hallway",
		profile: "",
		img: "",
	},
	{
		id: 13,
		full_name: "Danyel Amar",
		title: "surf coach",
		certificated: "No ISA",
		level: "Free Surfer",
		location: "Legian",
		profile: "",
		img: "",
	},
];
