export const SurfAthlete = [
  {
    id: 1,
    full_name: "dylan wilconxen",
    nickname: "dylan",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_dylan wilconxen.webp",
  },
  {
    id: 2,
    full_name: "made balon",
    nickname: "balon",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_made balon.webp",
  },
  {
    id: 3,
    full_name: "made nesa",
    nickname: "made nesa",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_made nesa.webp",
  },
  {
    id: 4,
    full_name: "lidia kato",
    nickname: "lidia",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_lidia kato.webp",
  },
  {
    id: 5,
    full_name: "nala rabik",
    nickname: "nala",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_nala rabik.webp",
  },
  {
    id: 6,
    full_name: "suri jabrik",
    nickname: "suri",
    age: "15",
    region: "indonesia",
    profile_image: "/assets/program/isa-junior/isa_junior_suri jabrik.webp",
  },
];
